name: BPoR Production Smoke Tests
on:
  workflow_dispatch:
  schedule:
    - cron: "30 6 * * *"
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: URL=https://bepartofresearch.nihr.ac.uk/ npx playwright test
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

  slack-failure:
    name: Send slack message failure
    needs: [test]
    runs-on: ubuntu-latest
    if: failure()
    steps:
      - uses: technote-space/workflow-conclusion-action@v2
      - name: Slack Notify
        if: github.ref == 'refs/heads/main'
        uses: rtCamp/action-slack-notify@v2.2.0
        env:
          SLACK_WEBHOOK: ${{ secrets.NIHR_ALERTS_SLACK_WEBHOOK }}
          SLACK_COLOR: "failure"
          SLACK_MESSAGE: "BPoR (PROD) smoke tests have failed"
          SLACK_TITLE: "BPoR (PROD) SMOKE TESTS: FAILED"

  slack-success:
    name: Send slack message success
    needs: [test]
    runs-on: ubuntu-latest
    if: success()
    steps:
      - uses: technote-space/workflow-conclusion-action@v2
      - name: Slack Notify
        if: github.ref == 'refs/heads/main'
        uses: rtCamp/action-slack-notify@v2.2.0
        env:
          SLACK_WEBHOOK: ${{ secrets.NIHR_ALERTS_SLACK_WEBHOOK }}
          SLACK_COLOR: "success"
          SLACK_MESSAGE: "BPoR (PROD) smoke tests have passed"
          SLACK_TITLE: "BPoR (PROD) SMOKE TESTS: SUCCESS"
